config/routes.rb
Rails.application.routes.draw do
  get 'questions/ask'
  get 'questions/answer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
    @your_question
  end

  def answer
    @your_question = params[:your_question]
    if @your_question == "i am going to work right now!"
      @coach_answer = "Great!"
    elsif @your_question.end_with?("?")
      @coach_answer = "Silly question, get dressed and go to work!"
    else
      @coach_answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<body>
<h1>Questions#answer</h1>
<p>Find me in app/views/questions/answer.html.erb</p>

<p><strong><%= @your_question %></strong></p>
<p><%= @coach_answer %></p>

<%= link_to "Ask!", questions_ask_path %>
</body>

app/views/questions/ask.html.erb
<body>
<h1>Questions#ask</h1>
<p>Find me in app/views/questions/ask.html.erb</p>
<form class="form" action=/questions/answer>
  <input type="text" name="your_question">
  <input type="submit" value="Ask!" class="btn">
</form>
</body>